### ISSUE TITLE
Threadsafety: ChartMogul::ChartMogulError: Configuration for account_token not set

### ISSUE THREAD

**Issue by cberkom** [chartmogul/chartmogul-ruby#105]
We've started getting this error sporadically, after upgrading from 1.5.2 to 1.6.2:
> ChartMogul::ChartMogulError: Configuration for account_token not set

In our application.rb file, Chartmogul is configured this way:

```ruby
    # ChartMogul
    config.after_initialize do
      ChartMogul.account_token = Core.config.chart_mogul_account_token
      ChartMogul.secret_key = Core.config.chart_mogul_secret_key
    end
```

These settings are always available when we run a Rails console, but the error crops up pretty often when we make ChartMogul calls in web and background processes.

I think it might have to do with **[the change to enable thread safety](https://github.com/chartmogul/chartmogul-ruby/commit/0df3f2dbe0bf8ce0714adb5d7c28da6af0fb3e92#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)**, leading to the settings being present for some threads but not others. Could you clarify how the configuration is supposed to work in a multi-threaded environment?

**Comment by pkopac** [comment]
Hello @cberkom,

please use the `global_` prefix (see README) to be able to set it once in the initializer and use it in different threads. You'll need to update to the new version 1.7.3.
