### ISSUE TITLE
Getting undefined method `api_key=' for ChartMogul:Module (NoMethodError)

### ISSUE THREAD

**Issue by jonfer** [chartmogul/chartmogul-ruby#129]
Hello,

I'm trying to use the gem in a Ruby on Rails 6.0.0 project with Ruby 2.5.0 but I'm getting this error: undefined method `api_key=' for ChartMogul:Module (NoMethodError)

I'm placing a file named chartmogul.rb with the following content:
`ChartMogul.api_key = '<API key goes here>'`

Is there anything that I'm doing wrong? Or the gem doesn't work with the version of Rails/Ruby that I'm using?

**Comment by pkopac** [comment]
@jonfer I assume you've resolved this quickly yourself. Is there anything we can improve in the README to make setup of the library easier?

**Comment by santigolucass** [comment]
I'm having the same issue, what did you do to solve @jonfer ?

**Comment by jonfer** [comment]
@santigolucass an old version of the gem was being installed. Because one of the gems I already had was at an older version that the new charmogul gem didn't support, so it was installing an old version of chartmogul.

**Comment by santigolucass** [comment]
Thanks man! @jonfer
