### ISSUE TITLE
 undefined method `global_api_key=' for ChartMogul:Module (NoMethodError)

### ISSUE THREAD

**Issue by santigolucass** [chartmogul/chartmogul-ruby#130]
Hello, im trying to implement ChartMogul in a RoR application and I'm getting the below error when I try to set the `global_api_key`, any ideas on how to fix that?

`undefined method `global_api_key=' for ChartMogul:Module (NoMethodError)`

ruby 2.6.6
rails 4.2.11.3
gem 'chartmogul-ruby', require: 'chartmogul'

```ruby
ChartMogul.global_api_key = <KEY>
```
`config/initializers/chartmogul.rb`

**Comment by sbrych** [comment]
Hey @santigolucass, can you make sure you're using the latest version? We've updated the API of the gem some time ago and README reflects how the new (3.x) version works
