### ISSUE TITLE
Faraday 2.0 support?

### ISSUE THREAD

**Issue by rickydalziel** [chartmogul/chartmogul-ruby#134]
Chartmogul depends on an old version of faraday: faraday (~> 1.0)

This is causing conflicts with other installed gems.

Are there any plans for upgrading to allow support for Faraday 2.0?

**Comment by jessicahearn** [comment]
We're in the process of resolving a few blockers to certain dependency upgrades at the moment, some of which involve Faraday. We haven't had the upgrading of Faraday on our list as a goal specifically, but I'll look into including that as part of the upgrade process.

**Comment by WillTaylor22** [comment]
Cheers Jessica!

**Comment by adamzapasnik** [comment]
any update on this?

**Comment by jessicahearn** [comment]
We've now released [v3.2.0](https://github.com/chartmogul/chartmogul-ruby/releases/tag/v3.2.0), which supports Faraday 2.7. Thanks for your patience! Please let us know if you encounter any difficulties.
