### ISSUE TITLE
Cancel customer subscription raise an error

### ISSUE THREAD

**Issue by SirNicholas** [chartmogul/chartmogul-ruby#22]
Look at official doc example:
```ruby
customer = ChartMogul::Import::Customer.all(external_id:"cus_0001").first
subscription = customer.subscriptions.last
subscription.cancel(Time.utc(2016, 1, 15))
```

Last line is raising an error:
```ruby
ChartMogul::SchemaInvalidError: JSON schema validation hasn't passed.
```

The problem is in this line: https://github.com/chartmogul/chartmogul-ruby/blob/master/lib/chartmogul/api/actions/custom.rb#L14

Thanks))

**Comment by jasonl** [comment]
Hi @SirNicholas - thanks for that. We'll investigate this shortly.
