### ISSUE TITLE
v1.1.9 tag and changelog

### ISSUE THREAD

**Issue by sj26** [chartmogul/chartmogul-ruby#51]
Howdy! Could you please tag v1.1.9 so https://github.com/chartmogul/chartmogul-ruby/compare/v1.1.7...v1.1.9 works, and update [the changelog](https://github.com/chartmogul/chartmogul-ruby/blob/master/changelog.md), so we can figure out if the update might impact us?

**Comment by spyrbri** [comment]
Done. Please find it [here](https://github.com/chartmogul/chartmogul-ruby/releases/tag/v1.1.9).
Another release is coming out soon. 
We will also update the releases as soon as possible.

**Comment by sj26** [comment]
Yes, thank you! 🙇🏻
