### ISSUE TITLE
Tagging a new release with faraday retry

### ISSUE THREAD

**Issue by vbalazs** [chartmogul/chartmogul-ruby#52]
Hello!

Could you tag and release a new version with #49 please? We see some timeout errors and this would help us a lot to avoid these noisy errors.

Thanks in advance!

**Comment by pkopac** [comment]
Hi @vbalazs! Thank you for the notice. I am sorry, it looks like I forgot to release it, it's there now:
https://github.com/chartmogul/chartmogul-ruby/releases/tag/v1.2.0

**Comment by vbalazs** [comment]
@pkopac sorry, I just tested the new release now and it seem it can break things because we must change the minimum required faraday version in the gemspec:

currently `spec.add_dependency 'faraday', '~>0.9'`

if I see it correctly faraday `0.15.0` introduced the `retry_statuses` option so I think the gem should require minimum that version... otherwise in our case it can happen that we receive a lot of test failures with `undefined method `retry_statuses=' for #<Faraday::Request::Retry::Options:XXX>` instead of giving a dependency error while doing bundle update.

What do you think?

**Comment by pkopac** [comment]
Please use `1.2.1`.
