### ISSUE TITLE
Update faraday dependency?

### ISSUE THREAD

**Issue by pcraston** [chartmogul/chartmogul-ruby#67]
Chartmogul depends on an old version of faraday: `faraday (~> 0.15.0)`

This is causing conflicts with other installed gems.

Are there any plans for upgrading to a most recent version of faraday?

**Comment by pkopac** [comment]
Hello @pcraston, thanks for the report. Do you require 1.0.0, or is 0.17 enough for your purposes?

**Comment by pcraston** [comment]
Hi @pkopac We've got one dependency that requires 0.16 and another that requires 1.0.0.

So 0.17 would be an improvement and 1.0.0 even better! 😄

**Comment by pkopac** [comment]
We've released [v1.5.1](https://github.com/chartmogul/chartmogul-ruby/releases/tag/v1.5.1) using 0.17. We'll try to release v1.6.0 with `faraday 1.0.0` this quarter.

**Comment by ikanade** [comment]
Sorry for the delay, we just released [v1.6.3](https://github.com/chartmogul/chartmogul-ruby/releases/tag/v1.6.3) with faraday updated to v1.0.x
